### ISSUE TITLE
How to use the pre-trained models?

### ISSUE THREAD

**Issue by ankurssharma96** [salu133445/musegan#29]
I am unable to figure out how to generate music with the help of pre-trained models by looking at the code. Can anyone tell me what changes do I have to make in the code for that?

**Comment by dianyo** [comment]
you can use load function [here](https://github.com/salu133445/musegan/blob/master/musegan/model.py#L138)
and then use save sample function [here](https://github.com/salu133445/musegan/blob/master/musegan/model.py#L153)

I haven't try this by myself yet, but I think it can be done by this.

**Comment by salu133445** [comment]
We have updated the code to v3. It should now be easier to load the pretrained models. Please refer to the README file to see how to use the pretrained models.

**Comment by notrandom34** [comment]
Thanks for updating! I still don't understand how  to generate music. The inference script runs without any error, but it doesn't output anything.
